# Generated by Django 4.2.9 on 2024-05-19 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERC20Tx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100, verbose_name='Hash')),
                ('fromAddr', models.CharField(max_length=100, verbose_name='From address')),
                ('toAddr', models.CharField(max_length=100, verbose_name='To address')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('tokenAddress', models.CharField(max_length=100, verbose_name='Token Address')),
            ],
        ),
        migrations.CreateModel(
            name='NativeTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100, verbose_name='Hash')),
                ('blockNumber', models.IntegerField(verbose_name='Block number')),
                ('fromAddr', models.CharField(max_length=100, verbose_name='From address')),
                ('toAddr', models.CharField(max_length=100, verbose_name='To address')),
                ('tokenAddress', models.CharField(max_length=100, verbose_name='Token Address')),
                ('blockHash', models.CharField(max_length=100, verbose_name='Block Hash')),
                ('gasPrice', models.IntegerField(verbose_name='Gas price')),
                ('inputTx', models.TextField(verbose_name='Input tx')),
                ('gas', models.IntegerField(verbose_name='Gas')),
                ('nonce', models.IntegerField(verbose_name='Nonce')),
                ('transactionIndex', models.IntegerField(verbose_name='Transaction Index')),
                ('v', models.TextField(verbose_name='v')),
                ('r', models.TextField(verbose_name='r')),
                ('s', models.TextField(verbose_name='s')),
                ('erc20Txs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.erc20tx')),
            ],
        ),
    ]
