# Generated by Django 4.2.9 on 2024-05-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nativetx',
            name='id',
        ),
        migrations.AlterField(
            model_name='nativetx',
            name='hash',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Hash'),
        ),
    ]
