# Generated by Django 4.2.9 on 2024-05-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_nativetx_erc20txs_erc20tx_nativetx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nativetx',
            name='r',
            field=models.CharField(max_length=100, verbose_name='r'),
        ),
        migrations.AlterField(
            model_name='nativetx',
            name='s',
            field=models.CharField(max_length=100, verbose_name='s'),
        ),
        migrations.AlterField(
            model_name='nativetx',
            name='v',
            field=models.CharField(max_length=100, verbose_name='v'),
        ),
    ]
